export const ActionTypes = {
  Login: 'LOGIN',
  Register: 'REGISTER',
  Logout: 'LOGOUT',
  Customer_Services: 'Customer_Services',
  Store_Service: 'Store_Service',
  Remove_Service: 'Remove_Service',
  Reset_Customer_Services: 'Reset_Customer_Services',
  Get_Banks: 'Get_Banks',
  Reset_Get_Banks: 'Reset_Get_Banks',
  Get_News: 'Get_News',
  Reset_Get_News: 'Reset_Get_News',
  Get_Seminars: 'Get_Seminars',
  Reset_Get_Seminars: 'Reset_Get_Seminars',
  ShowLoading: 'SHOW_LOADING',
  HideLoading: 'HIDE_LOADING',
};
